FROM maven:3.6.3-jdk-8-slim as build
WORKDIR /usr/src/recipes-list
COPY pom.xml ./
RUN mvn dependency:go-offline
COPY ./src ./src
RUN mvn clean install -DskipTests


FROM openjdk:8-jre-alpine as PROD
WORKDIR /usr/bin/recipes-list
COPY --from=build /usr/src/recipes-list/target/recipes-list-0.0.1-SNAPSHOT.jar .

FROM PROD 
CMD ["java", "-jar", "recipes-list-0.0.1-SNAPSHOT.jar" ]
