FROM maven:3.6.3-jdk-8-slim as build
WORKDIR /usr/src/recipes-reviews
COPY pom.xml ./
RUN mvn dependency:go-offline
COPY ./src ./src
RUN mvn clean install -DskipTests


FROM openjdk:8-jre-alpine as PROD
WORKDIR /usr/bin/recipes-reviews
COPY --from=build /usr/src/recipes-reviews/target/recipes-reviews-0.0.1-SNAPSHOT.jar .

FROM PROD 
CMD ["java", "-jar", "recipes-reviews-0.0.1-SNAPSHOT.jar" ]
